version: "3"


vars:
tasks:
  default:
    cmd: task --list

  proto-gen-order-core:
    desc: "Генерация protobuf файлов в сервисе OrderCore"
    cmds:
      - |
        protoc \
        -I ./order-core/api \
        --go_out ./order-core/pkg/ --go_opt paths=source_relative \
        --go-grpc_out ./order-core/pkg/ --go-grpc_opt paths=source_relative \
        ./order-core/api/v1/*.proto
  proto-gen-gateway:
    desc: "Генерация protobuf файлов в сервисе API Gateway"
    cmds:
      - |
        protoc \
        -I api-gateway/vendor.api \
        --go_out=api-gateway/pkg --go_opt=paths=source_relative \
        --go-grpc_out=api-gateway/pkg --go-grpc_opt=paths=source_relative \
        api-gateway/vendor.api/order/v1/order.proto

  proto-gen-kitchen:
    desc: "Генерация protobuf файлов в сервисе Kitchen Service"
    cmds:
      - |
        protoc \
        -I kitchen-queue/vendor.api \
        -I kitchen-queue/api \
        --go_out=kitchen-queue/pkg --go_opt=paths=source_relative \
        --go-grpc_out=kitchen-queue/pkg --go-grpc_opt=paths=source_relative \
        kitchen-queue/vendor.api/order/v1/order.proto \
        kitchen-queue/api/v1/kitchen.proto